### ISSUE TITLE
test about PASTE

### ISSUE THREAD

**Issue by wtao0221** [micchie/paste#1]
Hi,

I build netmap from the latest git version. But when I run ```phttpd -b 0 -i eth0 -c```, it shows
```
955.428029 nm_start [583] running on 40 cpus (have 40)
955.428060 nmreq_open [507] overriding MEMID 0
955.428065 nmreq_open [511] overriding EXTRA 0
955.428069 nmreq_open [515] overriding RING_CFG
955.428072 nmreq_open [523] overriding ringid 0x0 flags 0x8000
955.447982 nm_start [647] mapped 41376 at 0x7fa915a5d000
955.448013 get_vnet_hdr_len [294] Port requires virtio-net header, length = 56
ioctl: Cannot allocate memory
955.490902 nm_start [709] failed in attach ioctl
Working on stack:0: 1 queues, 1 threads and 40 cpus.
955.491082 nm_start [726] aborting
```

Messages from ```dmesg | tail```:
```
[ 6992.537967] 955.474356 [1010] netmap_obj_malloc         no more 2_ring objects
[ 6992.546041] 955.482435 [1906] netmap_mem2_rings_create  Cannot allocate RX_ring
```

And if I omit ```-i``` option, the httpd launches correctly.

BTW, there maybe something wired.

After I insert kernel modules (i.e., ```netmap.ko``` and ```ixgbe.ko``` in my case) and test whether I correctly install netmap, I run ```sudo pkt-gen -i eth0 -f tx -n 500111222 -l 60 -w 5``` without running ```sudo pkt-gen -i eth0 -f rx``` at first. But it still outputs 14Mpps throughput.

**Comment by wtao0221** [comment]
Plus, there are some abnormalities when I run ```phttpd``` without ```-i``` option.

The ```phttpd``` does not report any pps in the output.

And the performance of wrk is only about 280k rps under option ```-d 30 -t 4 -c 50```.

**Comment by micchie** [comment]
Regarding "Cannot allocate RX_ring" error, can you try following?
echo 16 > /sys/module/netmap/parameters/priv_if_num
echo 160 > /sys/module/netmap/parameters/priv_ring_num
echo 640000 > /sys/module/netmap/parameters/priv_buf_num
echo 33024 > /sys/module/netmap/parameters/priv_ring_size
(If the same error persists, adjust the values.

Also, don’t forget to set offload setting properly, like:
ethtool -A eth2 autoneg off tx off rx off
ethtool -K eth2 tx off rx off tso off lro off
ethtool -K eth2 gso off gro off
ethtool -K eth2 tx-checksum-ipv4 on

Regarding phttpd without "-i" option, it is correct that phttpd does not output anything (it's just my lazy...). And in that case, 280k rps with 50 parallel connections seems reasonable - see the 1 core, 64B RPC workload numbers at https://www.micchie.net/paste/. Or do you have other thoughts?

**Comment by wtao0221** [comment]
Hi, @micchie 

Sorry for the late reply.

This still does not work no matter how I change the parameters (priv_if_num, priv_ring_num, priv_buf_num, priv_ring_size, if_num, ring_num, buf_num, ring_size). Below is my NIC configuration:
```
ethtool -k enp6s0f0
Features for enp6s0f0:
Cannot get device udp-fragmentation-offload settings: Operation not permitted
rx-checksumming: off
tx-checksumming: on
        tx-checksum-ipv4: off [fixed]
        tx-checksum-ip-generic: on
        tx-checksum-ipv6: off [fixed]
        tx-checksum-fcoe-crc: on [fixed]
        tx-checksum-sctp: off
scatter-gather: on
        tx-scatter-gather: on
        tx-scatter-gather-fraglist: off [fixed]
tcp-segmentation-offload: off
        tx-tcp-segmentation: off
        tx-tcp-ecn-segmentation: off [fixed]
        tx-tcp-mangleid-segmentation: off
        tx-tcp6-segmentation: off
udp-fragmentation-offload: off
generic-segmentation-offload: off
generic-receive-offload: off
large-receive-offload: off
rx-vlan-offload: on
tx-vlan-offload: on
ntuple-filters: off
receive-hashing: on
highdma: on [fixed]
rx-vlan-filter: on
vlan-challenged: off [fixed]
tx-lockless: off [fixed]
netns-local: off [fixed]
tx-gso-robust: off [fixed]
tx-fcoe-segmentation: on [fixed]
tx-gre-segmentation: on
tx-gre-csum-segmentation: on
tx-ipxip4-segmentation: on
tx-ipxip6-segmentation: on
tx-udp_tnl-segmentation: on
tx-udp_tnl-csum-segmentation: on
tx-gso-partial: on
tx-sctp-segmentation: off [fixed]
tx-esp-segmentation: off [fixed]
fcoe-mtu: off [fixed]
tx-nocache-copy: off
loopback: off [fixed]
rx-fcs: off [fixed]
rx-all: off
tx-vlan-stag-hw-insert: off [fixed]
rx-vlan-stag-hw-parse: off [fixed]
rx-vlan-stag-filter: off [fixed]
l2-fwd-offload: off [fixed]
hw-tc-offload: off
esp-hw-offload: off [fixed]
esp-tx-csum-hw-offload: off [fixed]
rx-udp_tunnel-port-offload: off
```
Here is the output of ```dmesg | tail```:
```
[ 4813.201659] 193.948055 [ 780] netmap_update_config      configuration changed for eth0: txring 40 x 512, rxring 40 x 512, rxbufsz 2048
[ 4813.215164] 193.961564 [ 780] netmap_update_config      configuration changed for stack:enp6s0f0: txring 40 x 512, rxring 40 x 512, rxbufsz 2048
[ 4813.255547] 194.001942 [1010] netmap_obj_malloc         no more 2_ring objects
[ 4813.263619] 194.010019 [1906] netmap_mem2_rings_create  Cannot allocate RX_ring
[ 4892.262980] 273.010220 [1010] netmap_obj_malloc         no more 3_ring objects
[ 4892.271053] 273.018298 [1906] netmap_mem2_rings_create  Cannot allocate RX_ring
```
After I change the ```priv_if_num, priv_ring_num, and etc.```
```
[ 4912.245624] 292.993079 [1010] netmap_obj_malloc         no more 4_ring objects
[ 4912.253695] 293.001154 [1906] netmap_mem2_rings_create  Cannot allocate TX_ring
```


And, regarding the performance of ```phttpd w/o "-i" option```, sorry for my careless mistake, I did not notice the unit of y-axis. 

However, I can not figure out how this works. I mean that ```"-i"``` option is to specify the NIC. But I can not run the ```phttpd``` w/ ```-i``` option, right? So why ```phttpd``` w/o ```-i``` launches successfully?

**Comment by wtao0221** [comment]
And,

I am using a ```X520-DA2 Dual-port 10G NIC``` (ixgbe driver) w/ ```ubuntu 16.04 LTS``` and I upgrade the kernel to 4.14.0.

**Comment by micchie** [comment]
Resolved offline. I also added detailed installation procedures at Section 2.4 in https://www.micchie.net/paste/

**Comment by wtao0221** [comment]
Thanks!
